### ISSUE TITLE
Gitlab template-asset - install.sh not working

### ISSUE THREAD

**Issue by suseendare** [port-labs/template-assets#33]
I am trying to run install.sh as part of Gitlab template.
https://github.com/port-labs/template-assets/blob/main/gitlab/install.sh

Lines 33, 34, and 35 have spaces before and after = and it's not working.

**Comment by suuus** [comment]
Thank you for raising this issue @suseendare ✨!
We've fixed this in the script. Can you let us know it this is resolved for you?
